### ISSUE TITLE
API: Create Events

### ISSUE THREAD

**Issue by goelsonali** [Women-Coding-Community/wcc-api#12]
<img width="1309" alt="image" src="https://github.com/Women-Coding-Community/wcc-api/assets/3664747/26571be9-fb87-4dae-869e-09152a7120af">

<img width="1263" alt="image" src="https://github.com/Women-Coding-Community/wcc-api/assets/3664747/01d6e530-4ed8-4bb6-b9ea-52247bbef09f">

**Comment by kikilondon** [comment]
@goelsonali Can I add this component to attributes.yml, or does it need a single yml file?

**Comment by kikilondon** [comment]
@goelsonali @dricazenck 


![Image](https://github.com/Women-Coding-Community/wcc-api/assets/108157135/cb7c0d83-733d-4dd3-9208-ab7c2256bc49)



![Image](https://github.com/Women-Coding-Community/wcc-api/assets/108157135/2fa645b7-a44c-487f-9be4-c10959950e39)



![Image](https://github.com/Women-Coding-Community/wcc-api/assets/108157135/4cba3d68-1ac6-4a32-85d1-aac409196bae)




- created  new  obj called eventCard (arrays of 4 with event Resources link) 

- moved HeroSection to attribute.yml file
